---
- name: Install vagrant
  hosts: all
  gather_facts: False
  tags: vm,vagrant
  tasks:
    - name: Install vagrant
      homebrew:
        name: vagrant
      ignore_errors: True # ignore errors when vagrant is already installed
