---
- name: Install powerlevel10k
  hosts: all
  gather_facts: False
  tags: zsh
  tasks:
    - name: Install powerlevel10k
      ansible.builtin.git:
        repo: 'https://github.com/romkatv/powerlevel10k.git'
        dest: '~/.oh-my-zsh/custom/themes/powerlevel10k'
        update: yes
