---
- name: Install intellij
  hosts: all
  gather_facts: False
  tags: graphical,ide,intellij
  vars:
    intellij_macos_zsh: |
        export PATH="$PATH:/Applications/IntelliJ IDEA.app/Contents/MacOS"
        alias idea="idea ."
  tasks:
    - name: Install intellij
      homebrew_cask:
        name: intellij-idea
    - name: Add intellij executable to PATH
      copy:
        content: '{{ intellij_macos_zsh }}'
        dest: ~/.oh-my-zsh/custom/intellij-macos.zsh
        mode: 0755
