---
- name: Install jenv
  hosts: all
  tags: java,jenv
  tasks:
    - name: Install jenv
      homebrew:
        name: jenv
    - name: Register JDKs in jenv
      shell: eval "$(jenv init -)" && jenv add {{ item }}
      environment:
        PATH: "{{ ansible_env.PATH }}:~/.jenv/bin"
      args:
        executable: /bin/bash
      register: jenv_add
      failed_when: "'not a valid path to java installation' in jenv_add.stdout"
      changed_when: "'already present' not in jenv_add.stdout"
      loop:
        - /Library/Java/JavaVirtualMachines/temurin-8.jdk/Contents/Home
        - /Library/Java/JavaVirtualMachines/openjdk-11.jdk/Contents/Home
        - /Library/Java/JavaVirtualMachines/openjdk-17.jdk/Contents/Home
        - /Library/Java/JavaVirtualMachines/openjdk-21.jdk/Contents/Home
    - name: Fix major versions JDKs in jenv
      file:
        src: "{{ item.src }}"
        dest: "{{ item.destination }}"
        state: link
      loop:
        - { destination: ~/.jenv/versions/8, src: /Library/Java/JavaVirtualMachines/temurin-8.jdk/Contents/Home }
        - { destination: ~/.jenv/versions/11, src: /Library/Java/JavaVirtualMachines/openjdk-11.jdk/Contents/Home }
        - { destination: ~/.jenv/versions/17, src: /Library/Java/JavaVirtualMachines/openjdk-17.jdk/Contents/Home }
        - { destination: ~/.jenv/versions/21, src: /Library/Java/JavaVirtualMachines/openjdk-21.jdk/Contents/Home }
    - name: Enable jenv export plugin
      shell: eval "$(jenv init -)" && jenv enable-plugin export
      register: jenv_enable_plugin
      changed_when: "'already enabled' not in jenv_enable_plugin.stdout"
      environment:
        PATH: "{{ ansible_env.PATH }}:~/.jenv/bin"
      args:
        executable: /bin/bash
    - name: Enable jenv maven plugin
      shell: eval "$(jenv init -)" && jenv enable-plugin maven
      register: jenv_enable_plugin
      changed_when: "'already enabled' not in jenv_enable_plugin.stdout"
      environment:
        PATH: "{{ ansible_env.PATH }}:~/.jenv/bin"
      args:
        executable: /bin/bash
