---
- name: Install nvm
  hosts: all
  gather_facts: False
  tags: javascript,nvm
  tasks:
    - name: Make sure nvm.zsh is present
      file:
        path: "~/.oh-my-zsh/custom/nvm.zsh"
        state: touch
        mode: 0700
        access_time: preserve
        modification_time: preserve
    - name: Add nvm variables to zsh
      lineinfile:
        path: "~/.oh-my-zsh/custom/nvm.zsh"
        state: present
        line: '{{ item }}'
      loop:
        - 'export NVM_DIR="$HOME/.nvm"'
        - '[ -s "$HOMEBREW_PREFIX/opt/nvm/nvm.sh" ] && \. "$HOMEBREW_PREFIX/opt/nvm/nvm.sh" # This loads nvm'
        - '[ -s "$HOMEBREW_PREFIX/opt/nvm/etc/bash_completion.d/nvm" ] && \. "$HOMEBREW_PREFIX/opt/nvm/etc/bash_completion.d/nvm" # This loads nvm bash_completion'
