---
- name: Symlink this repository executable
  hosts: all
  tags: wac
  gather_facts: False
  tasks:
    - name: Add this repository ./provision symlink to /usr/local/bin
      become: true
      copy:
        content: "#!/bin/bash\ncd {{ playbook_dir }}/..\n./provision.sh"
        dest: /usr/local/bin/provision
        mode: 0755
