---
- name: Install and setup brew and brew packages
  hosts: all
  gather_facts: False
  tags: brew
  tasks:
    - name: Check if homebrew is installed
      shell:
        cmd: brew --help
      register: homebrew_check
      changed_when: false
    - name: Install homebrew
      shell:
        cmd: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      when: homebrew_check.rc != 0
    - name: Add cask-versions
      shell:
        cmd: brew tap homebrew/cask-versions
    - name: Upgrade homebrew packages
      homebrew:
        upgrade_all: "true"
      register: result
      until: result is successful
      when: homebrew_check.rc == 0
    - name: Install gnu-tar # needed by ansible unarchive module
      homebrew:
        name: gnu-tar
    - name: Install graphical tools
      tags: graphical
      homebrew_cask:
        name: "{{ item }}"
        state: present
      loop:
        - double-commander
        - flycut # clipboard manager
        - foobar2000
        - gimp
        - libreoffice
        - iterm2
        - keepassxc
        - mucommander
        - postman
        - signal
        - spectacle
        - spotify
        - sublime-text
        - thunderbird
        - vlc
    - name: Install console tools
      tags: console
      homebrew:
        name: "{{ item }}"
        state: present
      loop:
        - hexyl
        - jq
        - midnight-commander
        - pipx
        - nmap
        - tmux
        - tmuxinator
        - unzip
        - vagrant
        - wget
        - qemu
        - yarn
        - zbar # to scan QR codes from image or camera
