---
- import_playbook: upgrade-system.yml
- import_playbook: install-brew-packages.yml
- import_playbook: add-self-symlink-to-bin.yml

- import_playbook: git/git.yml
- import_playbook: git/git-global-config.yml
- import_playbook: git/lazygit.yml

- import_playbook: zsh/zsh.yml
- import_playbook: zsh/oh-my-zsh.yml
- import_playbook: zsh/powerlevel10k.yml

- import_playbook: various/broot.yml
- import_playbook: various/imagemagick.yml
- import_playbook: various/viddy.yml
- import_playbook: various/zoom.yml
- import_playbook: various/zoxide.yml

- import_playbook: vim/vim.yml
- import_playbook: vim/vim-plug.yml
- import_playbook: vim/neovim.yml